[package]
name = "audio_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
eframe = "0.31.1"
cpal = "0.16.0"
rustfft = "6.3.0"
num-complex = "0.4.6"
anyhow = "1.0.98"
egui_plot = "0.32.1"
pitch-detection = "0.3.0"